# -*- coding: utf-8 -*-
"""functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oOId2MRwqtqWB0R4C3Y85kqslQMvmjxl
"""

def calculate_total(marks):
    """
    Returns the sum of all marks in the list.
    """
    total = 0
    for mark in marks:
        total += mark
    return total


def calculate_average(marks):
    """
    Returns the average of marks by calling calculate_total().
    """
    if len(marks) == 0:
        return 0
    total = calculate_total(marks)
    return total / len(marks)


def get_grade(average):
    """
    Returns grade based on average marks.
    """
    if average > 90:
        return "A"
    elif average > 75:
        return "B"
    else:
        return "C"


def display_report(marks):
    """
    Displays total, average, and grade using other functions.
    """
    total = calculate_total(marks)
    average = calculate_average(marks)
    grade = get_grade(average)

    print("Total:", total)
    print("Average:", average)
    print("Grade:", grade)


# Test case
marks_list = [88, 76, 95, 60, 82]
display_report(marks_list)